version: '3.7'


services:

    bot:
        build: .
        restart: always
        depends_on:
            - redis
        env_file:
            - .env
        environment:
            TZ: UTC
            REDIS_URL: redis://redis:6379/0
            _TOKEN: <YOUR_TOKEN>
        volumes:
            - .:/app
        networks:
            - my_network

    redis:
        image: "redis:alpine"
        restart: always
        environment:
            TZ: UTC
        ports:
            - "6379:6379"
        networks:
            - my_network


networks:
  my_network:
    external: false
